### PR TITLE
WIP: Compare components

### PR DESCRIPTION
**Pull request by bcipolli**
This is work-in-progress where I'll compare components across left and right hemispheres, and left/right to those found with both hemispheres.

To do that, I plan to:
* Write code that scores how similar two components are
* Uses those scores to match up components across hemis
* Plots those components side-by-side showing a score.

This should give us a rough sense of asymmetries.

@atsuch just flagging you as a heads-up. Creating "WIP" pull requests before we've actually done the work, is a good way to stay synchronized in our work and potentially use code even before it's complete.

### CODE REVIEW

**Comment by atsuch** [comment]
Thank you!

I was starting to work on this part a bit, although it’s not committed yet. I was just using simple correlations to compare R and L as well as components from whole brain. Did you have other kind of scores in mind?

Even though we’re not there yet, the step after this would be to compare the contrast maps associated with matched components and characterize shared and different terms associated terms?

I’ll try to find time here and there to work on it a bit more but with the little monster around me all the time it’s hard to do anything… 

Thank you so much for starting to work on it!

Ami

**Comment by bcipolli** [comment]
Ah, oops-sorry! I match the components based on L1 norm (just subtract and sum the absolute deviations).

I should have something done in a couple of hours; just trying to find a way to store the ICA terms inside each image. I *thought* I had a way, but ... apparently no :-/

**Comment by bcipolli** [comment]
If you can check out the master branch, and submit your changes as a PR on top of that (so I can take a look & combine the code), that'd be great. I started refactoring the code (to make it more modular), so it won't be easy to directly apply your changes to what I'm doing here...

**Comment by bcipolli** [comment]
This seems to be working, though the results are messy. I think we need to review the images being used and make sure they're reasonable. But I think this is ready to go... though the code probably looks drastically different!

**Comment by bcipolli** [comment]
To compare /combine R and L to compare against bilateral, perhaps matching each to bilateral, then combining that way. then doing the full comparison.

If R and L don't uniquely match to bilateral, however, there's going to be some problem... perhaps just take the best match, and drop any ICs that don't have R/L pair.

**Comment by bcipolli** [comment]
I'm going to merge this; it works, and it's already been refactored lol

**Pull request merged**
